version: '2'
services: 
  nginx:
    image: nginx 
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enable:/etc/nginx/sites-enable
      - ./nginx/sites-ssl:/etc/ssl

    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  nexus:
    image: sonatype/nexus3:latest
    restart: always
    volumes:
      - ./nexus/NEXUS_DATA:/nexus-data
    ports:
      - "9091:8081"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  gogsData:
    image: 'busybox'
    tty: true
    volumes:
      - './gogs/data:/data'
      - './gogs/mysql:/var/lib/mysql'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  gogs:
    image: gogs/gogs
    restart: 'always'
    ports:
      - "22:22"
      - "5000:3000"
    links:
      - jenkins
    volumes_from:
      - 'gogsData'
    extra_hosts:
      - "jenkins.ci-cd-meetup.com:10.5.0.2"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    # command: bash -c "echo '10.5.0.5 jenkins.ci-cd-meetup.com' >> /etc/hosts && cat /etc/hosts"
  
  mysql:
    image: mariadb:10.1
    restart: 'always'
    volumes_from:
      - 'gogsData'
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: kmiko
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: kmiko
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  jenkins:
    image: jenkins:latest
    restart: always
    ports:
      - 9080:8080   
    cap_add:
     - SYS_ADMIN
    volumes:
      - ./jenkins/JENKINS_HOME:/var/jenkins_home
      - nginx:/var/jenkins_home/nginx
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    extra_hosts:
      - "nexus.ci-cd-meetup.com:10.5.0.2"
      - "git.ci-cd-meetup.com:10.5.0.2"

volumes: 
  nexus:
  jenkins1:
  mongo-dev:
  nginx:
  db-data:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
